apiVersion: v1
kind: Namespace
metadata:
  name: rag-system
  labels:
    name: rag-system
    app: rag-knowledge-assistant
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rag-resource-quota
  namespace: rag-system
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "20"
    secrets: "10"
    configmaps: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: rag-limit-range
  namespace: rag-system
spec:
  limits:
  - type: Container
    default:
      cpu: "1"
      memory: 2Gi
    defaultRequest:
      cpu: 500m
      memory: 1Gi
    max:
      cpu: "4"
      memory: 8Gi
    min:
      cpu: 100m
      memory: 128Mi
