apiVersion: v1
kind: Secret
metadata:
  name: rag-secrets
  namespace: rag-system
type: Opaque
data:
  # Base64 encoded values (replace with actual values)
  SECRET_KEY: eW91ci1zZWNyZXQta2V5LWNoYW5nZS1pbi1wcm9kdWN0aW9u
  OPENAI_API_KEY: c2steW91ci1vcGVuYWktYXBpLWtleS1oZXJl
  PINECONE_API_KEY: eW91ci1waW5lY29uZS1hcGkta2V5
  DATABASE_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: rag-system
type: Opaque
data:
  POSTGRES_USER: cmFnX3VzZXI=
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  POSTGRES_DB: cmFnX2Ri
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: rag-system
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmQ=
